version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: likeyun_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db
    networks:
      - webnet

  php:
    build: ./docker/php
    container_name: likeyun_php
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - webnet

  db:
    image: mysql:8.0
    container_name: likeyun_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-likeyun}
      MYSQL_USER: ${MYSQL_USER:-likeyun}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-likeyunpass}
      TZ: Asia/Shanghai
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin:5
    container_name: likeyun_pma
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 64M
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet: 